// ============================================================
// OwnMerit - Mock Data for Development
// ============================================================

import type {
  Task,
  Reminder,
  Resident,
  Appointment,
  MeritProgress,
  Voucher,
} from "./types";
import { MILESTONES } from "./constants";

// ---- Tasks ----
export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: "Make your bed",
    description: "Make your bed neatly before 9am",
    category: "chore",
    status: "pending",
    meritPoints: 5,
    dueDate: "2026-02-12",
    dueTime: "09:00",
    requiresProof: true,
  },
  {
    id: "t2",
    title: "Morning hygiene routine",
    description: "Brush teeth, shower, and get dressed",
    category: "hygiene",
    status: "pending",
    meritPoints: 5,
    dueDate: "2026-02-12",
    dueTime: "08:30",
    requiresProof: false,
  },
  {
    id: "t3",
    title: "Attend literacy class",
    description: "Room 3, Ground Floor - Mrs. Thompson",
    category: "education",
    status: "pending",
    meritPoints: 10,
    dueDate: "2026-02-12",
    dueTime: "10:00",
    requiresProof: true,
  },
  {
    id: "t4",
    title: "GP Appointment",
    description: "Dr. Patel at the Health Centre, bring your ID",
    category: "appointment",
    status: "pending",
    meritPoints: 10,
    dueDate: "2026-02-12",
    dueTime: "14:00",
    requiresProof: true,
  },
  {
    id: "t5",
    title: "Cook dinner (group rota)",
    description: "It's your turn on the cooking rota tonight",
    category: "chore",
    status: "pending",
    meritPoints: 8,
    dueDate: "2026-02-12",
    dueTime: "17:30",
    requiresProof: true,
  },
  {
    id: "t6",
    title: "Social activity - Board games",
    description: "Join others in the common room for game night",
    category: "social",
    status: "completed",
    meritPoints: 5,
    dueDate: "2026-02-11",
    dueTime: "19:00",
    requiresProof: false,
    completedAt: "2026-02-11T19:45:00",
  },
];

// ---- Reminders ----
export const MOCK_REMINDERS: Reminder[] = [
  {
    id: "r1",
    title: "Take morning medication",
    description: "Remember to take your medication with breakfast",
    time: "08:00",
    date: "2026-02-12",
    priority: "high",
    recurrence: "daily",
    category: "health",
    isActive: true,
    isDismissed: false,
  },
  {
    id: "r2",
    title: "Key worker meeting",
    description: "Weekly check-in with Sarah in office 2",
    time: "11:00",
    date: "2026-02-12",
    priority: "medium",
    recurrence: "weekly",
    category: "appointment",
    isActive: true,
    isDismissed: false,
  },
  {
    id: "r3",
    title: "Tidy your room",
    description: "Room inspection at 5pm - tidy up beforehand",
    time: "16:00",
    date: "2026-02-12",
    priority: "medium",
    recurrence: "weekdays",
    category: "chore",
    isActive: true,
    isDismissed: false,
  },
  {
    id: "r4",
    title: "Evening walk",
    description: "30-minute walk around the grounds",
    time: "18:00",
    date: "2026-02-12",
    priority: "low",
    recurrence: "daily",
    category: "health",
    isActive: true,
    isDismissed: false,
  },
];

// ---- Merit Progress ----
export const MOCK_MERIT_PROGRESS: MeritProgress = {
  currentPoints: 68,
  totalEarned: 218,
  level: 3,
  milestones: MILESTONES.map((m) => ({
    ...m,
    achieved: m.pointsRequired <= 68,
  })),
  weeklyHistory: [
    { day: "Mon", points: 15 },
    { day: "Tue", points: 20 },
    { day: "Wed", points: 10 },
    { day: "Thu", points: 8 },
    { day: "Fri", points: 25 },
    { day: "Sat", points: 5 },
    { day: "Sun", points: 12 },
  ],
};

// ---- Vouchers ----
export const MOCK_VOUCHERS: Voucher[] = [
  {
    id: "v1",
    code: "OWNMERIT-2026-A1B2C3",
    value: 10,
    currency: "GBP",
    expiresAt: "2026-03-12",
    status: "available",
    retailer: "Tesco",
  },
  {
    id: "v2",
    code: "OWNMERIT-2026-D4E5F6",
    value: 10,
    currency: "GBP",
    expiresAt: "2026-02-28",
    redeemedAt: "2026-02-01",
    status: "redeemed",
    retailer: "Primark",
  },
];

// ---- Residents (Admin View) ----
export const MOCK_RESIDENTS: Resident[] = [
  {
    id: "res1",
    name: "James Wilson",
    roomNumber: "12",
    moveInDate: "2025-11-15",
    keyWorker: "Sarah Mitchell",
    meritPoints: 68,
    taskCompletion: 82,
    trafficLight: "green",
    recentTasks: MOCK_TASKS.slice(0, 3),
  },
  {
    id: "res2",
    name: "David Brown",
    roomNumber: "8",
    moveInDate: "2025-12-01",
    keyWorker: "Sarah Mitchell",
    meritPoints: 45,
    taskCompletion: 65,
    trafficLight: "amber",
    recentTasks: MOCK_TASKS.slice(1, 4),
  },
  {
    id: "res3",
    name: "Michael Taylor",
    roomNumber: "3",
    moveInDate: "2026-01-10",
    keyWorker: "Tom Henderson",
    meritPoints: 22,
    taskCompletion: 40,
    trafficLight: "red",
    recentTasks: MOCK_TASKS.slice(2, 5),
  },
  {
    id: "res4",
    name: "Ryan Clarke",
    roomNumber: "15",
    moveInDate: "2025-10-20",
    keyWorker: "Tom Henderson",
    meritPoints: 92,
    taskCompletion: 95,
    trafficLight: "green",
    recentTasks: MOCK_TASKS.slice(0, 2),
  },
  {
    id: "res5",
    name: "Chris Ahmed",
    roomNumber: "7",
    moveInDate: "2026-01-25",
    keyWorker: "Lisa Wong",
    meritPoints: 35,
    taskCompletion: 55,
    trafficLight: "amber",
    recentTasks: MOCK_TASKS.slice(3, 6),
  },
];

// ---- Appointments (Admin) ----
export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    residentId: "res1",
    residentName: "James Wilson",
    title: "GP Check-up",
    description: "Routine health check with Dr. Patel",
    date: "2026-02-14",
    time: "10:00",
    recurrence: "once",
    category: "health",
    location: "Health Centre",
    createdBy: "Sarah Mitchell",
  },
  {
    id: "a2",
    residentId: "res2",
    residentName: "David Brown",
    title: "Probation Meeting",
    description: "Monthly check-in with probation officer",
    date: "2026-02-15",
    time: "14:00",
    recurrence: "monthly",
    category: "appointment",
    location: "Office 3",
    createdBy: "Sarah Mitchell",
  },
  {
    id: "a3",
    residentId: "res3",
    residentName: "Michael Taylor",
    title: "Literacy Class",
    description: "Weekly literacy session",
    date: "2026-02-12",
    time: "10:00",
    recurrence: "weekly",
    category: "education",
    location: "Room 3, Ground Floor",
    createdBy: "Tom Henderson",
  },
];
